// Модуль содержит константы

const DATA_ERROR_MESSAGE_TIME = 5000;
const INITIAL_COMMENTS_COUNT = 5;
const VISIBLE_COMMENTS_COUNT_STEP = 5;
const MIN_PREVIEW_IMAGE_SCALE_VALUE = 0.25;
const MAX_PREVIEW_IMAGE_SCALE_VALUE = 1;
const PREVIEW_IMAGE_SCALE_STEP_VALUE = 0.25;
const MAX_HASHTAGS_COUNT = 5;
const TEXT_DESCRIPTION_LENGTH = 140;

export {
  DATA_ERROR_MESSAGE_TIME,
  INITIAL_COMMENTS_COUNT,
  VISIBLE_COMMENTS_COUNT_STEP,
  MIN_PREVIEW_IMAGE_SCALE_VALUE,
  MAX_PREVIEW_IMAGE_SCALE_VALUE,
  PREVIEW_IMAGE_SCALE_STEP_VALUE,
  MAX_HASHTAGS_COUNT,
  TEXT_DESCRIPTION_LENGTH
};
